version: '3'
services:
  app:
    container_name: backend121
    build: ./server/.
    env_file:
      - ./server/env_ports.env
    links:
      - mongo_db
    ports:
      - 5012:5000  
    depends_on:
      - mongo_db
  
  
  mongo_db:
    container_name: database1271
    image: mongo
